In [1]:
import polars as pl
data_pl = pl.read_csv(r"../data/train.csv",encoding="shift_jis")

In [2]:
data_pl

shape: (1_322, 1_559)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample    ┆ species   ┆ 樹種      ┆ 含水率    ┆ … ┆ 4011.3927 ┆ 4007.5356 ┆ 4003.6785 ┆ 3999.821 │
│ number    ┆ number    ┆ ---       ┆ ---       ┆   ┆ 1         ┆ ---       ┆ ---       ┆ 39       │
│ ---       ┆ ---       ┆ str       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ ---      │
│ i64       ┆ i64       ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 1         ┆ イチョウ  ┆ 216.12903 ┆ … ┆ 1.22818   ┆ 1.23087   ┆ 1.23354   ┆ 1.23219  │
│           ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 1         ┆ イチョウ  ┆ 210.75268 ┆ … ┆ 1.21074   ┆ 1.21508   ┆ 1.21901   ┆ 1.21846  │
│           ┆           ┆           ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ 1         ┆ イチョウ  ┆ 205.91397 ┆ … ┆ 1.162     ┆ 1.15341   ┆ 1.15139   ┆ 1.15403  │
│           ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ 1         ┆ イチョウ  ┆ 201.07526 ┆ … ┆ 1.11426   ┆ 1.11787   ┆ 1.11849   ┆ 1.11328  │
│           ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ 1         ┆ イチョウ  ┆ 196.23655 ┆ … ┆ 1.06962   ┆ 1.07056   ┆ 1.06459   ┆ 1.05612  │
│           ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 1868      ┆ 19        ┆ ホワイト  ┆ 13.372093 ┆ … ┆ 0.37515   ┆ 0.37348   ┆ 0.37089   ┆ 0.36545  │
│           ┆           ┆ オーク    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1869      ┆ 19        ┆ ホワイト  ┆ 13.081395 ┆ … ┆ 0.37331   ┆ 0.37256   ┆ 0.37196   ┆ 0.36702  │
│           ┆           ┆ オーク    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1870      ┆ 19        ┆ ホワイト  ┆ 12.5      ┆ … ┆ 0.37852   ┆ 0.37857   ┆ 0.37435   ┆ 0.36774  │
│           ┆           ┆ オーク    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1871      ┆ 19        ┆ ホワイト  ┆ 12.209302 ┆ … ┆ 0.37222   ┆ 0.37245   ┆ 0.37079   ┆ 0.36497  │
│           ┆           ┆ オーク    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1872      ┆ 19        ┆ ホワイト  ┆ 12.209302 ┆ … ┆ 0.37072   ┆ 0.37242   ┆ 0.37372   ┆ 0.37127  │
│           ┆           ┆ オーク    ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
data_new = data_pl.with_columns(
    pl.col("含水率").log().alias("含水率_log")
)

In [4]:
data_new

shape: (1_322, 1_560)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample    ┆ species   ┆ 樹種      ┆ 含水率    ┆ … ┆ 4007.5356 ┆ 4003.6785 ┆ 3999.8213 ┆ 含水率_l │
│ number    ┆ number    ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ 9         ┆ og       │
│ ---       ┆ ---       ┆ str       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│ i64       ┆ i64       ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 1         ┆ イチョウ  ┆ 216.12903 ┆ … ┆ 1.23087   ┆ 1.23354   ┆ 1.23219   ┆ 5.375876 │
│           ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 1         ┆ イチョウ  ┆ 210.75268 ┆ … ┆ 1.21508   ┆ 1.21901   ┆ 1.21846   ┆ 5.350685 │
│           ┆           ┆           ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ 1         ┆ イチョウ  ┆ 205.91397 ┆ … ┆ 1.15341   ┆ 1.15139   ┆ 1.15403   ┆ 5.327459 │
│           ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ 1         ┆ イチョウ  ┆ 201.07526 ┆ … ┆ 1.11787   ┆ 1.11849   ┆ 1.11328   ┆ 5.303679 │
│           ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ 1         ┆ イチョウ  ┆ 196.23655 ┆ … ┆ 1.07056   ┆ 1.06459   ┆ 1.05612   ┆ 5.279321 │
│           ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 1868      ┆ 19        ┆ ホワイト  ┆ 13.372093 ┆ … ┆ 0.37348   ┆ 0.37089   ┆ 0.36545   ┆ 2.59317  │
│           ┆           ┆ オーク    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1869      ┆ 19        ┆ ホワイト  ┆ 13.081395 ┆ … ┆ 0.37256   ┆ 0.37196   ┆ 0.36702   ┆ 2.571191 │
│           ┆           ┆ オーク    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1870      ┆ 19        ┆ ホワイト  ┆ 12.5      ┆ … ┆ 0.37857   ┆ 0.37435   ┆ 0.36774   ┆ 2.525729 │
│           ┆           ┆ オーク    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1871      ┆ 19        ┆ ホワイト  ┆ 12.209302 ┆ … ┆ 0.37245   ┆ 0.37079   ┆ 0.36497   ┆ 2.502198 │
│           ┆           ┆ オーク    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1872      ┆ 19        ┆ ホワイト  ┆ 12.209302 ┆ … ┆ 0.37242   ┆ 0.37372   ┆ 0.37127   ┆ 2.502198 │
│           ┆           ┆ オーク    ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [50]:
Ginkgo = data_new.filter(pl.col("樹種") == "イチョウ")

In [51]:
Ginkgo.head(1)

shape: (1, 1_560)
┌────────┬────────────┬──────────┬────────────┬───┬───────────┬───────────┬────────────┬───────────┐
│ sample ┆ species    ┆ 樹種     ┆ 含水率     ┆ … ┆ 4007.5356 ┆ 4003.6785 ┆ 3999.82139 ┆ 含水率_lo │
│ number ┆ number     ┆ ---      ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---        ┆ g         │
│ ---    ┆ ---        ┆ str      ┆ f64        ┆   ┆ f64       ┆ f64       ┆ f64        ┆ ---       │
│ i64    ┆ i64        ┆          ┆            ┆   ┆           ┆           ┆            ┆ f64       │
╞════════╪════════════╪══════════╪════════════╪═══╪═══════════╪═══════════╪════════════╪═══════════╡
│ 1      ┆ 1          ┆ イチョウ ┆ 216.129032 ┆ … ┆ 1.23087   ┆ 1.23354   ┆ 1.23219    ┆ 5.375876  │
└────────┴────────────┴──────────┴────────────┴───┴───────────┴───────────┴────────────┴───────────┘

In [52]:
!pip install --upgrade scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.11/site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.11/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.11/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [53]:
import lightgbm as lgb
import polars as pl

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [54]:
# --- データ ---
pl_df = data_new

# 目的変数
y = pl_df["含水率_log"].to_numpy()

# 特徴量（不要列を除外）
drop_cols = ["含水率", "含水率_log", "樹種", "sample number", "species number"]
feature_cols = [c for c in pl_df.columns if c not in drop_cols]

X = pl_df.select(feature_cols).to_numpy()
# --- 分割 ---
X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --- モデル ---
model = lgb.LGBMRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=-1,
)

# --- 学習 ---
model.fit(
    X_train, y_train,
    eval_set=[(X_valid, y_valid)],
    eval_metric="rmse",
    callbacks=[lgb.early_stopping(50)]
)

# --- 評価 ---
#pred = model.predict(X_valid)
#rmse = mean_squared_error(y_valid, pred, squared=False)

#print("RMSE:", rmse)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.062868 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 396525
[LightGBM] [Info] Number of data points in the train set: 1057, number of used features: 1555
[LightGBM] [Info] Start training from score 3.408297
Training until validation scores don't improve for 50 rounds
Did not meet early stopping. Best iteration is:
[495]	valid_0's rmse: 0.166102	valid_0's l2: 0.0275898

LGBMRegressor(learning_rate=0.05, n_estimators=500)

In [55]:
from sklearn.metrics import mean_squared_error
import numpy as np

mse = mean_squared_error(y_valid, pred)
rmse = np.sqrt(mse)
print("RMSE:", rmse)

RMSE: 0.18071874835146626

In [56]:
RMSE: 0.18071874835146626

## 差分

In [57]:
exclude_cols = ["sample number", "species number", 
                "樹種", "含水率", "含水率_log"]
num_cols = [c for c in pl_df.columns if c not in exclude_cols]

# 横方向の差分カラム名を作成
diff_cols = [f"{num_cols[i]}_diff_{num_cols[i+1]}"
             for i in range(len(num_cols)-1)]

# 横方向の差分を計算して新規カラムとして追加
diff_exprs = [
    (pl.col(num_cols[i+1]) - pl.col(num_cols[i])).alias(diff_cols[i])
    for i in range(len(num_cols)-1)
]

pl_diff_df = pl_df.with_columns(diff_exprs)

In [58]:
pl_diff_df

shape: (1_322, 3_114)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample    ┆ species   ┆ 樹種      ┆ 含水率    ┆ … ┆ 4015.2498 ┆ 4011.3927 ┆ 4007.5356 ┆ 4003.678 │
│ number    ┆ number    ┆ ---       ┆ ---       ┆   ┆ 2_diff_40 ┆ 1_diff_40 ┆ _diff_400 ┆ 5_diff_3 │
│ ---       ┆ ---       ┆ str       ┆ f64       ┆   ┆ 11.39271  ┆ 07.5356   ┆ 3.6785    ┆ 999.8213 │
│ i64       ┆ i64       ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 9        │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 1         ┆ イチョウ  ┆ 216.12903 ┆ … ┆ -0.00163  ┆ 0.00269   ┆ 0.00267   ┆ -0.00135 │
│           ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 1         ┆ イチョウ  ┆ 210.75268 ┆ … ┆ -0.00131  ┆ 0.00434   ┆ 0.00393   ┆ -0.00055 │
│           ┆           ┆           ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ 1         ┆ イチョウ  ┆ 205.91397 ┆ … ┆ -0.00755  ┆ -0.00859  ┆ -0.00202  ┆ 0.00264  │
│           ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ 1         ┆ イチョウ  ┆ 201.07526 ┆ … ┆ 0.00261   ┆ 0.00361   ┆ 0.00062   ┆ -0.00521 │
│           ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ 1         ┆ イチョウ  ┆ 196.23655 ┆ … ┆ 0.00396   ┆ 0.00094   ┆ -0.00597  ┆ -0.00847 │
│           ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 1868      ┆ 19        ┆ ホワイト  ┆ 13.372093 ┆ … ┆ -0.00145  ┆ -0.00167  ┆ -0.00259  ┆ -0.00544 │
│           ┆           ┆ オーク    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1869      ┆ 19        ┆ ホワイト  ┆ 13.081395 ┆ … ┆ -0.00242  ┆ -0.00075  ┆ -0.0006   ┆ -0.00494 │
│           ┆           ┆ オーク    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1870      ┆ 19        ┆ ホワイト  ┆ 12.5      ┆ … ┆ 0.00076   ┆ 0.00005   ┆ -0.00422  ┆ -0.00661 │
│           ┆           ┆ オーク    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1871      ┆ 19        ┆ ホワイト  ┆ 12.209302 ┆ … ┆ -0.00002  ┆ 0.00023   ┆ -0.00166  ┆ -0.00582 │
│           ┆           ┆ オーク    ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1872      ┆ 19        ┆ ホワイト  ┆ 12.209302 ┆ … ┆ -0.00035  ┆ 0.0017    ┆ 0.0013    ┆ -0.00245 │
│           ┆           ┆ オーク    ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [60]:
# --- データ ---
pl_df = pl_diff_df

# 目的変数
y = pl_df["含水率_log"].to_numpy()

# 特徴量（不要列を除外）
drop_cols = ["含水率", "含水率_log", "樹種", "sample number", "species number"]
feature_cols = [c for c in pl_df.columns if c not in drop_cols]

X = pl_df.select(feature_cols).to_numpy()
# --- 分割 ---
X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --- モデル ---
model = lgb.LGBMRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=-1,
)

# --- 学習 ---
model.fit(
    X_train, y_train,
    eval_set=[(X_valid, y_valid)],
    eval_metric="rmse",
    callbacks=[lgb.early_stopping(50)],
    n_jobs=4
)

# --- 評価 ---
#pred = model.predict(X_valid)
#rmse = mean_squared_error(y_valid, pred, squared=False)

#print("RMSE:", rmse)

TypeError: LGBMRegressor.fit() got an unexpected keyword argument 'n_jobs'

In [ ]:
from sklearn.metrics import mean_squared_error
import numpy as np

mse = mean_squared_error(y_valid, pred)
rmse = np.sqrt(mse)
print("RMSE:", rmse)